= Introduction

This document is intended as a reference for those working with the _Peppol Development Kit_ (Referred to as *PDK* from now on) for the first time.
Additionally, it is also intended to serve as a cookbook with self-contained references and solutions for common use cases.

== What is PDK?
*PDK* is a tool, developed by Peppol Development Team,
to generate HTML-based static websites for documentation of the Business Interoperability Specifications (BIS). The tool  provides means to define all business process lifecycle and its necessary properties to automate and standardize Peppol BIS documentation.


*PDK* allows developers to initiate, create, build, validate and migrate BIS documentation.
It also allows you to serve the documentation as a static webpage.

A developer can define a Peppol BIS process,
transactions,
semantic model,
syntax binding,
semantic rules,
codelists for certain data types,
XSD schemas and schematrons for the transactions of the process.

Using *PDK*, the developer then validates and builds static project artifacts
using the above-mentioned assets. The validations are performed against the
XSD schemas and schematron files defined in the project hierarchy.
The validation results are populated in the tool output.

PDK also supports running build and validation operations separately.
After completing build operation, you can generate static website documentation artifact
by running a separate `pdk hugo` command, which will generate the ultimate
static website artifact ready to be deployed to a server.

== Installation

PDK is available for running as a Docker container. It is available from the OpenPeppol container registry.

Please read https://docs.peppol.eu/peppol-ecr-login[peppol-ecr-login guide] before proceeding.
We will assume that you have installed docker and pulled the pdk image according to this guide.

After you have logged in and pulled the pdk image according to the above guide, we will be using the below command sequence.

[source,bash]
----
docker run --rm --pull=always -i \
   -v "$(pwd)":/src \
   070318080841.dkr.ecr.eu-west-1.amazonaws.com/pdk \
   pdk [TARGET_TASKS]
----

You can replace `[TARGET_TASKS]` section with the *tasks* that you want to execute.
Please see section <<PDK Tasks>> for the list of possible tasks.

[NOTE]
If you have cloned an already existing BiS project from OpenPeppol github, the above
command might probably exist in scripts named `docker-....bat` or `docker-...sh`.

== PDK Tasks

PDK Tasks are a set of commands for managing the build life cycle and publishing of
a PDK Bis project.
The following table contains PDK tasks and their corresponding descriptions.

[cols="4,6",frame=rows,grid=rows]
|===

|`build`
|Build all the processes

|`build-skip-tests`
|Build model, skip validations and prepare hugo site

|`clean`
|Clean the artifacts

|`config:{vscode\|devcontainer}`
|Configure vscode validation tool for the project or devcontainer for the project

|`hugo`
|Generate static website

|`migrate`
|Migrate an existing project from the old syntax to the new pdk module

|`run init`
|Create and initiate an empty project

|`serve`
|Serve the static site

|`validate`
|Validate sample transactions against XSD schemas and schematrons

|===

[CAUTION]
It's important to note that, when you execute the `clean` goal of PDK, the target directory is removed,
meaning you lose all compiled classes from previous builds.
That means, that PDK will have to rebuild all of your project again from scratch.
So if you have performed some manual editing to the generated files
under the target dir, you will lose them.
//end caution
